-- Bangladesh Industrial Intelligence
-- Public schema definition only. No production data belongs in GitHub.

create schema if not exists bii;

create table if not exists bii.collector_runs (
  run_id bigint generated by default as identity primary key,
  source_name text not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  mode text not null,
  status text not null,
  pages_requested integer not null default 0,
  records_discovered integer not null default 0,
  notes text
);

create table if not exists bii.source_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  run_id bigint references bii.collector_runs(run_id),
  source_name text not null,
  source_kind text not null,
  source_url text not null,
  retrieved_at timestamptz not null,
  source_reported_at timestamptz,
  source_total_records integer,
  http_status integer,
  content_sha256 text not null,
  raw_payload_path text,
  parser_version text not null,
  unique (source_name, source_url, content_sha256)
);

create table if not exists bii.organizations (
  organization_id bigint generated by default as identity primary key,
  canonical_name text not null,
  normalized_name text,
  created_at timestamptz not null default now(),
  notes text
);

create table if not exists bii.establishments (
  establishment_id bigint generated by default as identity primary key,
  dife_public_id bigint unique,
  canonical_name text,
  created_at timestamptz not null default now(),
  first_snapshot_id bigint references bii.source_snapshots(snapshot_id)
);

create table if not exists bii.organization_establishment_links (
  organization_id bigint not null references bii.organizations(organization_id),
  establishment_id bigint not null references bii.establishments(establishment_id),
  relationship_type text not null,
  source_origin text not null,
  evidence text,
  created_at timestamptz not null default now(),
  primary key (organization_id, establishment_id, relationship_type)
);

create table if not exists bii.establishment_observations (
  observation_id bigint generated by default as identity primary key,
  establishment_id bigint not null references bii.establishments(establishment_id),
  snapshot_id bigint not null references bii.source_snapshots(snapshot_id),
  source_record_key text,
  name_official_bn text,
  name_official_en text,
  sector_official_bn text,
  address_official text,
  upazila_official_bn text,
  district_official_bn text,
  division_official_bn text,
  class_official_bn text,
  establishment_type_official_bn text,
  status_official_bn text,
  row_sha256 text not null,
  observed_at timestamptz not null,
  unique (establishment_id, snapshot_id, row_sha256)
);

create table if not exists bii.licence_observations (
  licence_observation_id bigint generated by default as identity primary key,
  establishment_id bigint not null references bii.establishments(establishment_id),
  snapshot_id bigint not null references bii.source_snapshots(snapshot_id),
  licence_no text,
  old_licence_no text,
  registration_no text,
  old_registration_no text,
  licence_expiry_date date,
  source_origin text not null,
  observed_at timestamptz not null
);

create table if not exists bii.employment_observations (
  employment_observation_id bigint generated by default as identity primary key,
  establishment_id bigint not null references bii.establishments(establishment_id),
  snapshot_id bigint not null references bii.source_snapshots(snapshot_id),
  worker_component_1 integer,
  worker_component_2 integer,
  worker_total integer,
  source_origin text not null,
  observed_at timestamptz not null
);

create table if not exists bii.external_source_profiles (
  source_name text primary key,
  source_authority text not null,
  base_url text not null,
  public_access text not null,
  automation_policy_status text not null,
  collection_mode text not null,
  refresh_strategy text not null,
  site_specificity text not null,
  fields_json jsonb not null default '{}'::jsonb,
  last_verified_at timestamptz,
  notes text
);

create table if not exists bii.external_source_records (
  external_record_id bigint generated by default as identity primary key,
  source_name text not null references bii.external_source_profiles(source_name),
  source_url text,
  external_key text,
  entity_name text,
  site_text text,
  source_fields_json jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null,
  source_origin text not null,
  unique (source_name, external_key)
);

create table if not exists bii.external_record_versions (
  external_version_id bigint generated by default as identity primary key,
  external_record_id bigint not null references bii.external_source_records(external_record_id),
  snapshot_id bigint references bii.source_snapshots(snapshot_id),
  normalized_name text,
  normalized_site text,
  district_text text,
  upazila_text text,
  content_sha256 text not null,
  source_fields_json jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  observed_at timestamptz not null,
  unique (external_record_id, content_sha256)
);

create table if not exists bii.entity_links (
  entity_link_id bigint generated by default as identity primary key,
  establishment_id bigint references bii.establishments(establishment_id),
  organization_id bigint references bii.organizations(organization_id),
  external_record_id bigint not null references bii.external_source_records(external_record_id),
  match_type text not null check (match_type in ('EXACT_SITE','PROBABLE_SITE','ORGANIZATION_ONLY','AMBIGUOUS','NO_MATCH','SOURCE_FEASIBILITY_ONLY')),
  site_level_match boolean not null,
  evidence text,
  created_at timestamptz not null default now()
);

create table if not exists bii.match_evidence (
  match_evidence_id bigint generated by default as identity primary key,
  entity_link_id bigint not null references bii.entity_links(entity_link_id),
  evidence_type text not null,
  dife_value text,
  external_value text,
  result text not null,
  rule_version text not null,
  notes text
);

create table if not exists bii.validation_strata (
  stratum_code text primary key,
  stratum_type text not null check (stratum_type in ('SECTOR_FAMILY','GEOGRAPHY_FLOOR')),
  stratum_label text not null,
  target_n integer not null,
  priority integer not null default 1,
  inclusion_rule text not null,
  notes text
);

create table if not exists bii.validation_sample (
  validation_sample_id bigint generated by default as identity primary key,
  validation_label text not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  sector_family text,
  geography_group text,
  selection_stage text not null,
  selected_at timestamptz not null,
  detail_status text not null default 'PENDING' check (detail_status in ('PENDING','SUCCESS','FAILED','NOT_ATTEMPTED')),
  external_status text not null default 'NOT_ATTEMPTED' check (external_status in ('NOT_ATTEMPTED','STAGED','REVIEWED')),
  unique (validation_label, establishment_id)
);

create table if not exists bii.collection_errors (
  error_id bigint generated by default as identity primary key,
  run_id bigint references bii.collector_runs(run_id),
  source_name text not null,
  source_url text,
  stage text not null,
  establishment_id bigint references bii.establishments(establishment_id),
  dife_public_id bigint,
  error_type text,
  error_message text,
  occurred_at timestamptz not null,
  retryable boolean
);

create index if not exists establishments_dife_public_id_idx on bii.establishments (dife_public_id);
create index if not exists establishment_obs_district_idx on bii.establishment_observations (district_official_bn);
create index if not exists establishment_obs_sector_idx on bii.establishment_observations (sector_official_bn);
create index if not exists external_records_source_key_idx on bii.external_source_records (source_name, external_key);
create index if not exists entity_links_establishment_idx on bii.entity_links (establishment_id);
