-- Detail-validation checkpoint layer.
-- Public schema only; no production observations belong in GitHub.

create table if not exists bii.detail_checkpoints (
  validation_label text not null,
  checkpoint_n integer not null,
  state text not null check (state in ('LOCKED','READY','PASSED','FAILED')),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  primary key (validation_label, checkpoint_n)
);

create table if not exists bii.detail_requests (
  detail_request_id bigint generated by default as identity primary key,
  validation_label text not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  sequence_no integer not null,
  first_checkpoint integer not null,
  source_url text not null,
  status text not null default 'PLANNED'
    check (status in ('PLANNED','PARSED','FAILED','SKIPPED')),
  planned_at timestamptz not null,
  resolved_at timestamptz,
  staged_snapshot_id bigint references bii.source_snapshots(snapshot_id),
  parser_valid boolean,
  core_complete boolean,
  error_message text,
  unique (validation_label, establishment_id),
  unique (validation_label, sequence_no),
  unique (validation_label, source_url)
);

create table if not exists bii.detail_observations (
  detail_observation_id bigint generated by default as identity primary key,
  validation_label text not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  snapshot_id bigint not null references bii.source_snapshots(snapshot_id),
  name_en text,
  name_bn text,
  address text,
  upazila text,
  district text,
  division text,
  status text,
  licence_expiry_raw text,
  sector text,
  licence_no text,
  old_licence_no text,
  registration_no text,
  old_registration_no text,
  licence_class text,
  establishment_type text,
  worker_component_1 integer,
  worker_component_2 integer,
  worker_total integer,
  parser_valid boolean not null,
  core_complete boolean not null,
  core_present integer not null,
  core_expected integer not null,
  observed_at timestamptz not null,
  row_sha256 text not null,
  unique (validation_label, establishment_id, snapshot_id, row_sha256)
);

create table if not exists bii.detail_checkpoint_decisions (
  decision_id bigint generated by default as identity primary key,
  validation_label text not null,
  checkpoint_n integer not null,
  evaluated_at timestamptz not null,
  passed boolean not null,
  metrics_json jsonb not null,
  policy_json jsonb not null,
  reasons_json jsonb not null
);

create index if not exists detail_request_checkpoint_idx
  on bii.detail_requests(validation_label, first_checkpoint, status);

create index if not exists detail_observation_establishment_idx
  on bii.detail_observations(validation_label, establishment_id, detail_observation_id desc);

create index if not exists detail_decision_checkpoint_idx
  on bii.detail_checkpoint_decisions(validation_label, checkpoint_n, evaluated_at desc);
