-- Collection-policy and private run audit layer.
-- The public repository stores schema only, never production observations.

create table if not exists bii.access_policy_reviews (
  review_id bigint generated by default as identity primary key,
  source_name text not null,
  decision text not null check (decision in ('REVIEWED_ALLOWED','REVIEWED_RESTRICTED')),
  reviewed_at timestamptz not null,
  review_note text not null,
  allowed_hosts_json jsonb not null,
  allowed_path_prefixes_json jsonb not null,
  requests_per_minute numeric not null check (requests_per_minute > 0),
  max_retries integer not null check (max_retries >= 0),
  timeout_seconds numeric not null check (timeout_seconds > 0),
  recorded_at timestamptz not null
);

create table if not exists bii.detail_collection_runs (
  run_id bigint generated by default as identity primary key,
  validation_label text not null,
  checkpoint_n integer not null,
  policy_review_id bigint not null references bii.access_policy_reviews(review_id),
  started_at timestamptz not null,
  completed_at timestamptz,
  status text not null check (status in ('RUNNING','COMPLETED','FAILED')),
  attempted integer not null default 0 check (attempted >= 0),
  parsed integer not null default 0 check (parsed >= 0),
  failed integer not null default 0 check (failed >= 0),
  raw_directory text not null,
  notes text
);

create index if not exists detail_collection_run_checkpoint_idx
  on bii.detail_collection_runs(validation_label, checkpoint_n, started_at desc);
