-- Validation reporting and anomaly audit layer.
-- Public schema only; no production observations are committed to GitHub.

create table if not exists bii.validation_reports (
  report_id bigint generated by default as identity primary key,
  validation_label text not null,
  checkpoint_n integer not null,
  generated_at timestamptz not null,
  report_json jsonb not null
);

create table if not exists bii.validation_anomalies (
  anomaly_id bigint generated by default as identity primary key,
  report_id bigint not null references bii.validation_reports(report_id),
  establishment_id bigint references bii.establishments(establishment_id),
  sequence_no integer not null,
  anomaly_type text not null,
  severity text not null check (severity in ('CRITICAL','HIGH','MEDIUM','INFO')),
  list_value text,
  detail_value text,
  note text not null
);

create index if not exists validation_report_checkpoint_idx
  on bii.validation_reports(validation_label, checkpoint_n, generated_at desc);

create index if not exists validation_anomaly_type_idx
  on bii.validation_anomalies(report_id, severity, anomaly_type);
