-- External enrichment validation layer.
-- Extends the source/version/link structures introduced in 001_initial_schema.sql.

alter table bii.external_source_profiles
  add column if not exists default_linkage text,
  add column if not exists stable_key_rule text,
  add column if not exists eligible_sector_families_json jsonb,
  add column if not exists negative_inference_allowed boolean not null default false;

alter table bii.external_source_records
  add column if not exists district text,
  add column if not exists upazila text,
  add column if not exists first_retrieved_at timestamptz;

alter table bii.external_record_versions
  add column if not exists entity_name text,
  add column if not exists site_text text,
  add column if not exists district text,
  add column if not exists upazila text,
  add column if not exists source_updated_at_raw text;

alter table bii.entity_links
  add column if not exists validation_label text,
  add column if not exists source_name text,
  add column if not exists rule_version text;

alter table bii.match_evidence
  add column if not exists note text;

create table if not exists bii.enrichment_targets (
  enrichment_target_id bigint generated by default as identity primary key,
  validation_label text not null,
  source_name text not null references bii.external_source_profiles(source_name),
  establishment_id bigint not null references bii.establishments(establishment_id),
  eligible boolean not null,
  status text not null check (status in ('PENDING','STAGED','REVIEWED','OUT_OF_SCOPE')),
  planned_at timestamptz not null,
  unique (validation_label, source_name, establishment_id)
);

create table if not exists bii.enrichment_reports (
  report_id bigint generated by default as identity primary key,
  validation_label text not null,
  source_name text not null,
  generated_at timestamptz not null,
  coverage_json jsonb not null
);

create index if not exists enrichment_target_status_idx
  on bii.enrichment_targets(validation_label, source_name, status);

create index if not exists entity_link_validation_source_idx
  on bii.entity_links(validation_label, source_name, created_at desc);

create index if not exists enrichment_report_source_idx
  on bii.enrichment_reports(validation_label, source_name, generated_at desc);
