-- External candidate-search and resolution audit layer.

create table if not exists bii.external_candidate_runs (
  run_id bigint generated by default as identity primary key,
  validation_label text not null,
  source_name text not null references bii.external_source_profiles(source_name),
  generated_at timestamptz not null,
  max_candidates integer not null check (max_candidates > 0),
  staged_source_records integer not null check (staged_source_records >= 0),
  targets_considered integer not null check (targets_considered >= 0),
  candidates_generated integer not null check (candidates_generated >= 0),
  auto_selected integer not null check (auto_selected >= 0),
  ambiguous integer not null check (ambiguous >= 0),
  review_required integer not null check (review_required >= 0),
  no_staged_candidate integer not null check (no_staged_candidate >= 0)
);

create table if not exists bii.external_match_candidates (
  candidate_id bigint generated by default as identity primary key,
  run_id bigint not null references bii.external_candidate_runs(run_id),
  validation_label text not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  source_name text not null,
  external_record_id bigint not null references bii.external_source_records(external_record_id),
  shortlist_position integer not null check (shortlist_position > 0),
  priority_class text not null check (priority_class in (
    'P1_EXACT_NAME_SITE',
    'P2_EXACT_NAME',
    'P3_STRONG_NAME_SITE',
    'P4_STRONG_NAME',
    'P5_WEAK_NAME_SITE'
  )),
  name_strength text not null,
  name_token_overlap numeric,
  district_result text not null,
  upazila_result text not null,
  address_result text not null,
  address_overlap numeric,
  unique (run_id, establishment_id, external_record_id)
);

create table if not exists bii.external_resolution_outcomes (
  outcome_id bigint generated by default as identity primary key,
  run_id bigint not null references bii.external_candidate_runs(run_id),
  validation_label text not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  source_name text not null,
  outcome text not null check (outcome in (
    'AUTO_SELECTED',
    'AMBIGUOUS',
    'REVIEW_REQUIRED',
    'NO_STAGED_CANDIDATE'
  )),
  candidate_count integer not null check (candidate_count >= 0),
  selected_external_record_id bigint references bii.external_source_records(external_record_id),
  selected_match_type text,
  note text not null,
  applied_entity_link_id bigint references bii.entity_links(entity_link_id),
  unique (run_id, establishment_id)
);

create index if not exists external_candidate_run_source_idx
  on bii.external_candidate_runs(validation_label, source_name, generated_at desc);

create index if not exists external_candidate_target_idx
  on bii.external_match_candidates(run_id, establishment_id, shortlist_position);

create index if not exists external_resolution_outcome_idx
  on bii.external_resolution_outcomes(run_id, outcome, establishment_id);
