-- BGMEA/EPB source-index discovery and detail-fetch planning layer.

create table if not exists bii.external_index_runs (
  run_id bigint generated by default as identity primary key,
  source_name text not null references bii.external_source_profiles(source_name),
  seed_url text not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  status text not null check (status in ('RUNNING','COMPLETED','FAILED')),
  source_reported_total integer,
  source_reported_last_page integer,
  pages_planned integer not null default 1,
  pages_staged integer not null default 0,
  records_discovered integer not null default 0,
  unique_keys integer not null default 0,
  quality_json jsonb,
  notes text
);

create table if not exists bii.external_index_pages (
  index_page_id bigint generated by default as identity primary key,
  run_id bigint not null references bii.external_index_runs(run_id),
  page integer not null,
  source_url text not null,
  reason text not null,
  status text not null default 'PLANNED'
    check (status in ('PLANNED','STAGED','FAILED','SKIPPED')),
  planned_at timestamptz not null,
  staged_at timestamptz,
  snapshot_id bigint references bii.source_snapshots(snapshot_id),
  content_format text,
  records_parsed integer,
  source_reported_total integer,
  source_reported_last_page integer,
  error_message text,
  unique (run_id, page),
  unique (run_id, source_url)
);

create table if not exists bii.external_index_records (
  index_record_id bigint generated by default as identity primary key,
  source_name text not null references bii.external_source_profiles(source_name),
  source_key text not null,
  entity_name text not null,
  detail_url text not null,
  registration_no text,
  district text,
  upazila text,
  office_address text,
  factory_address text,
  first_seen_at timestamptz not null,
  unique (source_name, source_key)
);

create table if not exists bii.external_index_record_versions (
  index_version_id bigint generated by default as identity primary key,
  index_record_id bigint not null references bii.external_index_records(index_record_id),
  run_id bigint not null references bii.external_index_runs(run_id),
  index_page_id bigint not null references bii.external_index_pages(index_page_id),
  row_sha256 text not null,
  entity_name text not null,
  detail_url text not null,
  registration_no text,
  district text,
  upazila text,
  office_address text,
  factory_address text,
  observed_at timestamptz not null,
  unique (index_record_id, run_id, index_page_id, row_sha256)
);

create table if not exists bii.external_detail_requests (
  request_id bigint generated by default as identity primary key,
  source_name text not null references bii.external_source_profiles(source_name),
  source_key text not null,
  detail_url text not null,
  status text not null default 'PLANNED'
    check (status in ('PLANNED','FETCHED','FAILED','SKIPPED')),
  planned_at timestamptz not null,
  resolved_at timestamptz,
  external_record_id bigint references bii.external_source_records(external_record_id),
  error_message text,
  unique (source_name, source_key, detail_url)
);

create table if not exists bii.external_detail_request_targets (
  request_id bigint not null references bii.external_detail_requests(request_id),
  validation_label text not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  index_record_id bigint not null references bii.external_index_records(index_record_id),
  shortlist_position integer not null check (shortlist_position > 0),
  priority_class text not null,
  primary key (request_id, validation_label, establishment_id)
);

create index if not exists external_index_run_source_idx
  on bii.external_index_runs(source_name, started_at desc);

create index if not exists external_index_page_status_idx
  on bii.external_index_pages(run_id, status, page);

create index if not exists external_index_record_key_idx
  on bii.external_index_records(source_name, source_key);

create index if not exists external_index_version_run_idx
  on bii.external_index_record_versions(run_id, index_record_id);

create index if not exists external_detail_request_status_idx
  on bii.external_detail_requests(source_name, status, request_id);

create index if not exists external_detail_target_idx
  on bii.external_detail_request_targets(validation_label, establishment_id, request_id);
