-- Typed intelligence observations derived from versioned external source records.

create table if not exists bii.external_typed_observations (
  typed_observation_id bigint generated by default as identity primary key,
  external_version_id bigint not null references bii.external_record_versions(external_version_id),
  source_name text not null,
  observation_type text not null,
  scope text not null check (scope in ('SITE','ORGANIZATION')),
  value_text text,
  value_numeric numeric,
  unit text,
  raw_label text not null,
  raw_value text not null,
  source_updated_at_raw text,
  observed_at timestamptz not null,
  observation_sha256 text not null,
  unique (external_version_id, observation_sha256)
);

create table if not exists bii.linked_intelligence_observations (
  linked_intelligence_id bigint generated by default as identity primary key,
  entity_link_id bigint not null references bii.entity_links(entity_link_id),
  typed_observation_id bigint not null references bii.external_typed_observations(typed_observation_id),
  validation_label text not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  display_scope text not null check (display_scope in ('SITE','ORGANIZATION')),
  site_attributable boolean not null,
  linked_at timestamptz not null,
  unique (entity_link_id, typed_observation_id)
);

create index if not exists typed_observation_version_idx
  on bii.external_typed_observations(external_version_id, observation_type, scope);

create index if not exists linked_intelligence_establishment_idx
  on bii.linked_intelligence_observations(validation_label, establishment_id, linked_intelligence_id);
