-- Audited national DIFE snapshot universe.

create table if not exists bii.national_universe_runs (
  universe_id bigint generated by default as identity primary key,
  universe_label text not null unique,
  seed_url text not null,
  page_size integer not null check (page_size > 0),
  started_at timestamptz not null,
  completed_at timestamptz,
  status text not null check (status in ('RUNNING','COMPLETED','FAILED')),
  expected_total integer,
  pages_planned integer not null default 1,
  pages_staged integer not null default 0,
  unique_public_ids integer not null default 0,
  duplicate_public_ids integer not null default 0,
  eligible_for_national_analysis boolean not null default false,
  qc_json jsonb,
  notes text
);

create table if not exists bii.national_universe_pages (
  universe_id bigint not null references bii.national_universe_runs(universe_id),
  page integer not null,
  source_url text not null,
  status text not null default 'PLANNED'
    check (status in ('PLANNED','STAGED','FAILED','SKIPPED')),
  planned_at timestamptz not null,
  staged_at timestamptz,
  snapshot_id bigint references bii.source_snapshots(snapshot_id),
  records_parsed integer,
  source_reported_total integer,
  error_message text,
  primary key (universe_id, page),
  unique (universe_id, source_url)
);

create table if not exists bii.national_universe_page_members (
  universe_id bigint not null references bii.national_universe_runs(universe_id),
  page integer not null,
  establishment_id bigint not null references bii.establishments(establishment_id),
  observation_id bigint not null references bii.establishment_observations(observation_id),
  snapshot_id bigint not null references bii.source_snapshots(snapshot_id),
  primary key (universe_id, page, establishment_id)
);

create index if not exists national_universe_status_idx
  on bii.national_universe_runs(status, eligible_for_national_analysis);

create index if not exists national_universe_page_status_idx
  on bii.national_universe_pages(universe_id, status, page);

create index if not exists national_universe_member_idx
  on bii.national_universe_page_members(universe_id, establishment_id);
