-- Restartable national DIFE snapshot collection audit and recovery.

create table if not exists bii.national_snapshot_collection_runs (
  collection_run_id bigint generated by default as identity primary key,
  universe_id bigint not null references bii.national_universe_runs(universe_id),
  policy_review_id bigint not null references bii.access_policy_reviews(review_id),
  started_at timestamptz not null,
  completed_at timestamptz,
  status text not null check (status in ('RUNNING','COMPLETED','FAILED','ABORTED')),
  max_pages integer not null check (max_pages > 0),
  attempted integer not null default 0,
  staged integer not null default 0,
  failed integer not null default 0,
  raw_directory text not null,
  stop_reason text,
  notes text
);

create table if not exists bii.national_snapshot_page_attempts (
  attempt_id bigint generated by default as identity primary key,
  collection_run_id bigint not null references bii.national_snapshot_collection_runs(collection_run_id),
  universe_id bigint not null references bii.national_universe_runs(universe_id),
  page integer not null,
  source_url text not null,
  attempted_at timestamptz not null,
  completed_at timestamptz,
  status text not null check(status in (
    'FETCHED_STAGED','COLLECTION_FAILED','PARSE_FAILED','INTEGRITY_ABORT'
  )),
  http_status integer,
  fetch_attempts integer,
  content_sha256 text,
  raw_payload_path text,
  snapshot_id bigint references bii.source_snapshots(snapshot_id),
  source_reported_total integer,
  error_message text
);

create table if not exists bii.national_universe_recovery_events (
  recovery_event_id bigint generated by default as identity primary key,
  universe_id bigint not null references bii.national_universe_runs(universe_id),
  event_type text not null check(event_type in ('REQUEUE_FAILED','ABORT','RESTART')),
  page integer,
  related_universe_id bigint references bii.national_universe_runs(universe_id),
  created_at timestamptz not null,
  reason text not null
);

create index if not exists national_snapshot_collection_universe_idx
  on bii.national_snapshot_collection_runs(universe_id, started_at desc);

create index if not exists national_snapshot_attempt_page_idx
  on bii.national_snapshot_page_attempts(universe_id, page, attempt_id);

create index if not exists national_recovery_universe_idx
  on bii.national_universe_recovery_events(universe_id, created_at desc);
