-- Scope-aware first-order spatial exposure evidence.

create table if not exists bii.spatial_exposure_sources (
  source_name text primary key,
  authority text not null,
  methodology_note text not null,
  source_reference text,
  imported_at timestamptz not null
);

create table if not exists bii.spatial_exposure_observations (
  exposure_observation_id bigint generated by default as identity primary key,
  source_name text not null references bii.spatial_exposure_sources(source_name),
  domain text not null check(domain in (
    'CLIMATE_HAZARD','TRANSPORT_ACCESS','POWER_SYSTEM','ENVIRONMENTAL_REGULATORY'
  )),
  metric_code text not null,
  metric_label text not null,
  spatial_scope text not null check(spatial_scope in ('SITE','UPAZILA','DISTRICT')),
  establishment_ref text,
  district text,
  upazila text,
  value_text text,
  value_numeric double precision,
  unit text,
  direction text not null check(direction in (
    'HIGHER_MEANS_MORE_EXPOSURE','HIGHER_MEANS_LESS_EXPOSURE','CONTEXT_ONLY'
  )),
  source_vintage text,
  observed_at timestamptz,
  evidence_note text,
  observation_sha256 text not null,
  unique(source_name, observation_sha256)
);

create index if not exists spatial_exposure_source_idx
  on bii.spatial_exposure_observations(source_name, domain, metric_code);

create index if not exists spatial_exposure_district_idx
  on bii.spatial_exposure_observations(district, upazila, spatial_scope);

create index if not exists spatial_exposure_site_idx
  on bii.spatial_exposure_observations(establishment_ref, spatial_scope);
