-- Canonical Bangladesh administrative geography and staged DDM AWARE adapter.

create table if not exists bii.admin_geography_units (
  geo_ref text primary key,
  level text not null check(level in ('DIVISION','DISTRICT','UPAZILA')),
  division_code text not null,
  division_name_en text not null,
  division_name_bn text,
  district_code text,
  district_name_en text,
  district_name_bn text,
  upazila_code text,
  upazila_name_en text,
  upazila_name_bn text,
  source_name text not null,
  source_vintage text
);

create table if not exists bii.admin_geography_aliases (
  alias_id bigint generated by default as identity primary key,
  level text not null check(level in ('DIVISION','DISTRICT','UPAZILA')),
  alias text not null,
  normalized_alias text not null,
  geo_ref text not null references bii.admin_geography_units(geo_ref),
  source_name text not null,
  note text not null,
  unique(level, normalized_alias, geo_ref)
);

create table if not exists bii.ddm_aware_import_runs (
  import_id bigint generated by default as identity primary key,
  source_name text not null,
  source_reference text,
  source_vintage text,
  observed_at timestamptz not null,
  imported_at timestamptz not null,
  source_records integer not null,
  mapped_districts integer not null,
  observations_staged integer not null,
  unresolved_json jsonb not null
);

alter table bii.spatial_exposure_observations
  drop constraint if exists spatial_exposure_observations_domain_check;

alter table bii.spatial_exposure_observations
  add constraint spatial_exposure_observations_domain_check
  check(domain in (
    'CLIMATE_HAZARD',
    'DISASTER_RISK',
    'TRANSPORT_ACCESS',
    'POWER_SYSTEM',
    'ENVIRONMENTAL_REGULATORY'
  ));

alter table bii.spatial_exposure_observations
  add column if not exists canonical_geo_ref text
    references bii.admin_geography_units(geo_ref);

alter table bii.spatial_exposure_observations
  add column if not exists geography_match_type text;

alter table bii.spatial_exposure_observations
  add column if not exists source_geography_label text;

create index if not exists admin_geography_level_idx
  on bii.admin_geography_units(level, division_code, district_code, upazila_code);

create index if not exists admin_geography_alias_idx
  on bii.admin_geography_aliases(level, normalized_alias);

create index if not exists ddm_aware_import_time_idx
  on bii.ddm_aware_import_runs(imported_at desc);
